### ISSUE TITLE
Wrong owner of mounted data directory

### ISSUE THREAD

**Issue by cyberco** [sameersbn/docker-postgresql#22] opened 2015-03-10 16:29 UTC
Postgresql expects to be started by the user that owns the data directory. But that doesn't work when using a mounted volume.
```
docker run -d --name postgresql --publish 5432:5432 -v /Users/me/db:/var/lib/postgresql sameersbn/postgresql:9.4
```
Results in:
```
Starting PostgreSQL server...
LOG:  skipping missing configuration file "/var/lib/postgresql/9.4/main/postgresql.auto.conf"
2015-03-10 16:05:23 UTC [13-2] FATAL:  data directory "/var/lib/postgresql/9.4/main" has wrong ownership
2015-03-10 16:05:23 UTC [13-3] HINT:  The server must be started by the user that owns the data directory.
```
Somehow the '9.4' directory is created, but not 'main' directory in there, throwing above exception.

I'm on OSX using boot2docker.

**Comment by cyberco** [comment] 2015-03-11 15:37
After some digging this seems to be a tough problem with Docker. See for details:

https://github.com/docker/docker/issues/7198

Basically, the folder shared through the Volume is mounted by the user:group of the host. In the container the folder appears to have an owner with a number (uid) instead of a name. There is not possible to do a chmod from within the container to change ownership of the mounted volume (or subfolders). I've tried to give the 'postgres' user in the container the same uid (1000) as the owner of the mounted folder, but although that allowed dbinit to create the initial files, the next roadblock was with pg_xlog files:

```
LOG:  could not link file "pg_xlog/xlogtemp.40" to "pg_xlog/000000010000000000000001" (initialization of log file): Operation not permitted
FATAL:  could not open file "pg_xlog/000000010000000000000001": No such file or directory
child process exited with exit code 1
initdb: removing data directory "/var/lib/postgresql/9.4/main"
```

**Comment by sameersbn** [comment] 2015-03-11 15:53
@cyberco sorry for not replying earlier.
The container chmods the `/var/lib/postgresql` directory before starting postgresql server. The `/var/lib/postgresql/9.4/main` directory is created by the `initdb` command, which clearly is throwing the error.

Now, some filesystems (particularly windows filesystems) do not allow you to set directory permissions or ownerships the unix way. This basically means that `chown` and `chmod` have no effect on such filesystems and that probably is the root cause of your issue.

I have not used boot2docker much, so I cannot give you very clear advice on what you should do.

**Comment by sameersbn** [comment] 2015-03-11 15:55
p.s. generally such issues can be seen when using selinux on a linux host. But as you indicated, you are using OSX. So I think the docker issue you mentioned probably does not apply to your case. I could be wrong though.

**Comment by cyberco** [comment] 2015-03-11 16:03
@sameersbn thanks for your feedback! Yes, I'm on OSX so that doesn't apply. And the problem is indeed with `initdb` not allowing other owners for the directory where the data is stored. As I said, this is a rather fundamental problem for many users. I wanted to avoid data-only containers but as it seems it could be the only option I have, so I'm going to try that now.

**Comment by sameersbn** [comment] 2015-03-11 16:04
@cyberco however, you might want to try removing the `sameersbn/postgresql` image and the underlying `sameersbn/ubuntu` image and pulling the `sameersbn/postgresql` image again before retrying. A long time back such issues used to occur and simple removing the image and repulling usaually fixed this issue.

**Comment by sameersbn** [comment] 2015-03-11 16:07
Here is a hack you can try.
Do `chmod -R 102:106 /Users/me/db` on the host. This will effective give owner ship of the `/Users/me/db` directory to the postgres user of the container.

**Comment by cyberco** [comment] 2015-03-11 16:47
Tried, but that doesn't work either.

**Comment by sameersbn** [comment] 2015-03-11 17:00
thats a bummer

**Comment by cyberco** [comment] 2015-03-11 17:05
Tried using a dedicated container for data as described [here](https://docs.docker.com/userguide/dockervolumes/), but that doesn't work either. I guess I'll just use a volume and see where the container stores in on my host and use that directory for the time being until Docker solves this roadblock. Bummer indeed.

**Comment by sameersbn** [comment] 2015-03-12 03:53
@cyberco did you try removing the image and pulling it from the docker index?

**Comment by cyberco** [comment] 2015-03-12 11:00
Could that make a difference? The only thing in the Dockerfile I've changed to build a local image is to comment the Volumes. Those are not needed since I'm passing the volume mapping (local:container) as commandline arguments when starting a container from that image.

**Comment by sameersbn** [comment] 2015-03-12 11:25
@cyberco Long time ago users used to report such issues and as it turned out that during the pull the docker image was getting corrupt and the simplest way to fix that was to remove the image (and underlying images) and repull. It has been a while since anyone has reported this lately so I am not sure if the issue is taken care of by docker or if it is general knowledge to delete and retry. Whichever way, it is worth trying.

Even if you are passing the local mapping for the volumes, the VOLUME statement will not effect you in anyway. Meaning if the image is configured to mount a volume at `/var/lib/postgresql`, docker will not automount a volume at that location when you specify the mapping through the docker cli.

**Comment by cyberco** [comment] 2015-03-16 11:30
Pulling the latest image didn't solve anything. The issue remains with the access rights of the mounted directory. I guess I'll have to wait for Docker to address this issue.

**Comment by thomasleveil** [comment] 2015-06-18 13:17
@cyberco I add the `"pg_xlog/000000010000000000000001": No such file or directory` error when having the postgresql volumes on a Vagrant shared folder (Windows host). 
Moving the volume location to a normal folder did solved the issue.

See http://serverfault.com/questions/699966/fail-to-start-postgresql-when-used-with-vagrant

**Comment by sameersbn** [comment] 2015-06-22 17:22
@thomasleveil you are right. The only other way this can be fixed is by attaching a volume to your VM, formatted in one of the linux filesystems (eg. `ext4`).

**Comment by sameersbn** [comment] 2016-08-07 13:46
closing this issue since this is a platform issue. feel free to re-open if you disagree :stuck_out_tongue:

**Closed by sameersbn** 2016-08-07 13:46 UTC
